version: "3"
services:
  app:
    image: new
    platform: linux/amd64
    build: 
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 9000:8080
    tty: true
    command: app.handler
